### ISSUE TITLE
can't install everything search

### ISSUE THREAD

**Issue by Whisper1101** [Flow-Launcher/Flow.Launcher#2053] opened 2023-04-17 10:06 UTC
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/17/2023 17:03:27
Exception:
System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: Cannot create a stable subkey under a volatile parent key.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 35
   at Flow.Launcher.PublicAPIInstance.<>c__DisplayClass13_0.<ShowMsg>b__0() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 97
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.PublicAPIInstance.ShowMsg(String title, String subTitle, String iconPath, Boolean useMainWindowAsOwner) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 95
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 44
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 44
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Whisper1101** [comment] 2023-04-17 10:08
[2023-04-17.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11248826/2023-04-17.txt)

**Comment by Garulf** [comment] 2023-04-19 16:08
Looks like a duplicate of #2054 (And many others). Please continue discussion there. Thank you.

**Closed by Garulf** 2023-04-19 16:08 UTC
