### ISSUE TITLE
"Tab" for next item in search results

### ISSUE THREAD

**Issue by MaxHasBeenUsed** [Flow-Launcher/Flow.Launcher#2151] opened 2023-05-22 14:05 UTC
**Is your feature request related to a problem? Please describe.**

Can only go through items by arrow keys

**Describe the solution you'd like**

Press "Tab" key for next item, "Shift + Tab" for previous. Like in PowerToys Run and Listary

**Comment by JohnTheGr8** [comment] 2023-05-22 20:01
Hey, thank you for your feedback.

I suppose that what you want is to be able to navigate items with just your left hand on the keyboard.

The problem is, Flow already uses `Tab` as a mechanism for auto-completion. I'm afraid this doesn't leave any reasonable left-hand keys to use for the functionality you want... 🤷‍♂️

**Comment by Garulf** [comment] 2023-05-22 22:32
We chose tab to mimic behavior found in console shells like BASH, ZSH, and Powershell. 


Perhaps we could look into allowing this key to be customized?

**Comment by JohnTheGr8** [comment] 2023-05-23 21:12
imo complicating things by making this customizable would not be justified here... 

(if your right hand is not on the keyboard, it's probably on the mouse, and you can use that to navigate)

**Comment by VictoriousRaptor** [comment] 2023-05-24 05:14
> It could be confusing but Flow already allows people to change "Preview Hotkey" (similar to "Navigation Hotkey" or "Tab
Key Behavior") and "Open Result Modifier Key" (also a great feature). Maybe a third one wouldn't hurt?

I think "Tab Key Behavior" is the right way if we decide to implement such a feature. We barely have no keys for a new hotkey. 

> (if your right hand is not on the keyboard, it's probably on the mouse, and you can use that to navigate)

We still need to move right hand to touch arrow keys for navigation. Though open result modifier is surely better for instantly activating results.

**Comment by JamesNZL** [comment] 2023-06-12 03:48
Transferring my comment to #2182—

I second this idea; I seem to find myself wishing for this ability every couple days.

Have we thought about using `Alt` + `Tab` as the hotkey (it is possible to intercept this while Flow is open?)

I'd argue that a launcher isn't really an application that you `Alt` + `Tab` away from in the traditional sense (and the launcher just closes itself anyway), so I'd argue that intercepting the Windows hotkey probably isn't a UX problem.

**Comment by jjw24** [comment] 2023-06-13 12:52
From what I have read in issue 2182 and here, seems those that request for tab to go next result don't need the autocomplete feature. Perhaps VictoriousRaptor's idea for a "Tab Key Behaviour" is a good choice- customise it to allow the switch between either tab next or autocomplete.

Although, let's say once you have tabbed to go to the result you want, what's the hand action to activate the result? Use right hand to press enter or use left hand to press open result modifier? 

I am also still on the fence about the benefits of tab to go next as you still end up using your right hand, awkwardly moving to the right with your left or work your fingers for the modifier key presses.

**Comment by JamesNZL** [comment] 2023-06-13 13:01
> seems those that request for tab to go next result don't need the autocomplete feature

Not true for me; I'd want to keep `Tab` for autocomplete, and have some other way to cycle through the results.

> Although, let's say once you have tabbed to go to the result you want, what's the hand action to activate the result? Use right hand to press enter or use left hand to press open result modifier?

This is only if autocomplete isn't the desired action.
Take the following example:

1. I type `tgl` for the default hotkeys.
   > ![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/1a19a31c-6ccb-42b2-9d94-53bcfea038e0)

2. I want to cycle through the results to `stop`, which I currently have to use the arrow keys for.  This cycles through the results, *without* auto-filling the query.
   > ![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/2bf3eb38-7cdf-4ef7-9c88-b6e5037aa315)

3. Once I have highlighted `stop`, I hit `Tab` to autocomplete `tgl edit`, which moves to the next plugin state.
   > ![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/44986932/2000f158-2cc5-4309-a0cb-32575aa54bcb)

*Now* I need to hit `Enter`, but only at the very end—a way to cycle through the options can still be very useful for things with lots of stages.

**Comment by jjw24** [comment] 2023-06-14 11:59
Going to convert this to discussion until we can come up with a good solution.

**Closed as completed** 2023-06-14 11:59 UTC
Labels: enhancement
