### ISSUE TITLE
BUG: New windows launch to incorrect workspace using Flow and GlazeWM together

### ISSUE THREAD

**Issue by notblam** [Flow-Launcher/Flow.Launcher#1776] opened 2023-01-10 06:36 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

So I am trying to figure out how to make Flow Launcher and Glaze Window Manager work together.  Glaze can be found here.
https://github.com/lars-berger/GlazeWM

The bug is new windows are not launched to the expected workspace when running multiple monitors.  If I have windows active in workspace 1, then focus my empty workspace 3 on my 2nd monitor and attempt to launch a program using flow to that workspace, it incorrectly launches to workspace 1.  If I launch the program using the windows task bar instead of flow after selecting workspace 3, it works correctly.  This is suggesting to me that Flow launches applications differently than the built in windows task bar, and Flow may be trying to automatically place these windows next to previously focused windows or on the same monitor as a previously focused window.  This is not behavior I want and I'm desperately trying to figure out what is preventing these applications from working together. 

### To Reproduce

1. Run FlowLauncher
2. Run GlazeWM
3. Open a window on the first monitor/workspace
4. Switch to a second window/workspace using alt+3
5. Launch an application an observe it incorrectly go to workspace 1 instead of the intended workspace 2

### Screenshots

https://gyazo.com/506b8d8ce0eb7087d66c92e3b8980742
If you've never used a window manager the numbers "3" and "1" on the top left of my monitors is my current workspace.  There will be a box around the selected one.  My secondary monitor is vertical which is why screencap looks strange.

### Flow Launcher Version

v1.8.3

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by z1nc0r3** [comment] 2023-01-11 05:55
Looks like your FL is not the latest version. Please update FL to latest version (v1.11.0) and check if the issue still exists.

**Comment by VictoriousRaptor** [comment] 2023-01-12 07:18
GWM developers confirmed this issue is on their side and will be fixed.

**Closed** 2023-01-12 07:17 UTC
Labels: bug
