### ISSUE TITLE
Node trying to find modules in the wrong folder

### ISSUE THREAD

**Issue by gabrielcarloto** [Flow-Launcher/Flow.Launcher#1302] opened 2022-08-04 14:33 UTC
Just installed my plugin (search npm) from the plugin store and when I type the action keyword it shows this error:

```
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/04/2022 11:23:38
Exception:
System.IO.InvalidDataException: Search npm|node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Search'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I think the important line here is `Error: Cannot find module 'C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Search'`. While  the folder name is "Search npm-1.0.1", node is trying to find modules in "Search", not finding them and throwing this error.

**Comment by taooceros** [comment] 2022-08-04 14:34
Is it because of space?

**Comment by taooceros** [comment] 2022-08-04 14:43
I am not able to reproduce this issue. Maybe it is fixed in the latest preview? 
Could you give it a try and let me know whether it is reproducible  https://github.com/Flow-Launcher/Flow.Launcher/discussions/956

**Comment by gabrielcarloto** [comment] 2022-08-04 14:54
I installed it, but in the settings it shows version 1.9.4, is this correct? Also, the portable build does not open. Anyway, I think it updated because now it shows the plugin icon instead of the search icon.

It gave me the same error.

**Comment by taooceros** [comment] 2022-08-04 14:58
Yeah the version doesn't matter. ok I can now reproduce the issue. I will investigate soon.

**Comment by taooceros** [comment] 2022-08-04 15:03
@gabrielcarloto it's the issue of the bat files. I think you need to figure out someway to escape the space in the plugin directory (I think that's reasonable).
![image](https://user-images.githubusercontent.com/45326534/182881030-a3608774-47cf-4529-9055-8052859e729d.png)

**Comment by taooceros** [comment] 2022-08-04 15:05
yeah this can be fixed by simply add a `"` between the path

`node "%plugin_dir%/build/index.js" %*`

**Closed by taooceros** 2022-08-04 15:05 UTC

**Comment by gabrielcarloto** [comment] 2022-08-04 15:14
It works, thank you

**Comment by taooceros** [comment] 2022-08-04 15:15
No Problem. Is the script from the document? We should fix it.
