### ISSUE TITLE
BUG: Video Downloader plugibn

### ISSUE THREAD

**Issue by geniusjoelraj** [Flow-Launcher/Flow.Launcher#3072] opened 2024-11-12 14:43 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

cannot download yt videos using video downloader

### To Reproduce

1. try downloading an youtube video

### Screenshots

![image](https://github.com/user-attachments/assets/299439df-1f4c-4b09-85c7-13a77d3d5b78)

### Flow Launcher Version

1.19.4

### Windows Build Number

1000.22700.1041.0

### Error Log

<details>

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\geniu\AppData\Roaming\FlowLauncher\Logs\1.19.4\2024-11-12.txt
2. copy below exception message

Flow Launcher version: 1.19.4
OS Version: 22631.4317
IntPtr Length: 8
x64: True

Python Path: C:\Users\geniu\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 11/12/2024 20:12:14
Exception:
System.IO.InvalidDataException: 'yt-dlp' is not recognized as an internal or external command,
operable program or batch file.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteResultAsync(JsonRPCResult result) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 117
   at Flow.Launcher.Core.Plugin.JsonRPCPluginBase.<>c__DisplayClass18_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginBase.cs:line 89
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</details>

**Comment by NoPlagiarism** [comment] 2024-11-12 16:49
Duplicate of https://github.com/z1nc0r3/AnyVideo-Downloader-Flow-Plugin/issues/16

Unrelated to this repository

**Closed** 2024-11-12 22:07 UTC
Labels: bug
