### ISSUE TITLE
The option to use tab or alt+number to navigate between results [Describe Your Feature]

### ISSUE THREAD

**Issue by qwertyqwerty29** [Flow-Launcher/Flow.Launcher#2182] opened 2023-06-11 23:16 UTC
**Is your feature request related to a problem? Please describe.**

it's easier and faster to not have to use your right hand ,  and Tab button is used universally for navigation and it's much more important than autocomplete

**Describe the solution you'd like**

a choice for the user to use the old method of alt+number for navigation or the  newer method of Tab to go to the next result 

**Describe alternatives you've considered**

 if it's not the tab button at least make it another button , not two buttons as in "alt + number" 

**Additional context**

 why is autocomplete important to begin with? 

all you need to do is type the first few letters for the result to appear , and you can press enter and the result will be opened without it's name having to be written compeletely in the search box

if it's important for some users maybe it would be better to change the shortcut to another button

**Comment by JamesNZL** [comment] 2023-06-12 00:43
> all you need to do is type the first few letters for the result to appear , and you can press enter and the result will be opened without it's name having to be written compeletely in the search box

This isn't actually true in the general case—it is entirely up to plugin developers to decide what is auto-filled with `Tab`, and what happens with `Enter`.

That *might* be to auto-fill the same query, but it could actually be two different behaviours.

Having said that though, I do think this is a good idea—but I'd propose the hotkey to be `Alt` + `Tab` so as to not break users' muscle memory with `Tab` performing an autocomplete.

Although `Alt` + `Tab` is 'two buttons', I'd argue that it can be easier than having to read off the number for an `Alt` + `<number>` hotkey.

This is dependent on the ability to intercept `Alt` + `Tab` when Flow is active though.

**Comment by qwertyqwerty29** [comment] 2023-06-12 01:14
that's a good alternative , thanks for suggesting it

**Comment by deefrawley** [comment] 2023-06-12 03:27
This is a dupe of #2151 - please add to the conversation there

**Closed by deefrawley** 2023-06-12 03:27 UTC
Labels: enhancement
