### ISSUE TITLE
BUG: Flow Launcher got an error

### ISSUE THREAD

**Issue by QuickAsdf123456** [Flow-Launcher/Flow.Launcher#2920] opened 2024-08-22 05:51 UTC
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Any command I perform with the plugin gives an error.

### To Reproduce

1. (hotkey)  ___ (any command)
2. will produce this error

[2024-08-22.txt](https://github.com/user-attachments/files/16705896/2024-08-22.txt)

### Screenshots

Flow Launcher version: 1.19.0
OS Version: 22631.3880
IntPtr Length: 8
x64: True

Python Path: C:\Users\Kyxry\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Users\Kyxry\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 08/22/2024 06:46:36
Exception:
System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: e. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[T](IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Post(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.SkipNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Skip() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 207
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass37_0.<SingleResultInList>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 568
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Flow Launcher Version

1.19.0

### Windows Build Number

I'm on windows 11 -> Microsoft Windows [Version 10.0.22631.3880] 

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment] 2024-08-22 08:17
Hi do you have the Spotify plugin installed? If so can you uninstall it and restart Flow and see if the problem happens again?

**Comment by QuickAsdf123456** [comment] 2024-08-23 02:28
I do have it installed yes, but this problem is about the plugin, sorry if I didn't make it clear or if I posted it in the wrong place it is anytime I do any Spotify plugin command ext ext for example S (my hotkey for spotify plugin changed to this): S next = the error , S play = error 

ext ext , hope this makes more sense , sorry for the confusion this is my first time using github and I am no coder by any means I only installed Flow yesterday and plugin yesterday too.

**Comment by jjw24** [comment] 2024-08-23 07:40
Hi there, all good :)

This error is caused by the Spotify plugin, which is maintained separately by the plugin author, so it would usually be reported over at the plugin repo for the author to fix (I know unfortunately the error message that popped up has asked you to post it here instead).

I will close this one and please follow this issue for updates- https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/issues/41

**Closed by jjw24** 2024-08-23 07:40 UTC
Labels: bug
