### ISSUE TITLE
BUG: Using the {clipboard} function can easily cause the program to crash

### ISSUE THREAD

**Issue by thomasTAT** [Flow-Launcher/Flow.Launcher#2085] opened 2023-04-22 19:19 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Using the {clipboard} function to read the clipboard can easily cause the program to crash, probably because the my clipboard content is too long
![image](https://user-images.githubusercontent.com/109513632/233802541-9afbc3e5-6366-43b8-a1e2-c8bf8c838c43.png)
![image](https://user-images.githubusercontent.com/109513632/233802553-6f1ed4ed-057a-4aa5-83b1-232d2c229a87.png)

### Flow Launcher Version

1.14.1

### Windows Build Number

 10.0.22621.1555

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Garulf** [comment] 2023-04-22 19:23
Thank you very much for reporting this bug. 

I think this is related to your previous issue and will be easier to track in one spot.

duplicate of #2084

**Closed by Garulf** 2023-04-22 19:23 UTC
Labels: bug
