### ISSUE TITLE
When search window appears mouse cursor is triggered to highlight result where the cursor is positioned 

### ISSUE THREAD

**Issue by lotsocds** [Flow-Launcher/Flow.Launcher#2595] opened 2024-02-27 21:14 UTC
I'm a user coming from many years using Launchy.  Flow Launcher is fabulous and I plan to stick with it.  However, there is one useability issue that slows me down, thus this enhancement request.  

The request is when the Flow Launcher window opens always highlight the top list entry if the list is not empty, never highlight the list entry under the mouse until the mouse is moved.  To illustrate, please follow the steps below which show the undesired behavior at step 6 and the desired behavior at step 11.  Why?  Because my use case involves running the same program multiple times.  I'd like to hit the Alt-Space hotkey then Enter to start the top program in the list. If the mouse happens to be in the list area when Flow Launcher opens, the wrong program will be started.  Moving the mouse off the wrong entry or remembering to hit Alt-1 will work but both are quite awkward compared to just Alt-Space, Enter.

Thanks for considering and I hope this is possible.

1. Use hotkey to open Flow Launcher.  
2. Type a couple characters to populate the list.  
3. Put the mouse in the middle of the list, e.g. on the second entry.  Don't move it again.
4. Hit Esc to close the window.  

5. Reopen Flow Launcher using the hot key.  
6. Notice that the list entry under the mouse is highlighted. (Undesired behavior)

7. Backspace to clear the entry field.
8. Hit Esc to close the window.  
9. Reopen Flow Launcher using the hot key.  
10. Type a couple characters to populate the list.
11. Notice that the list entry under the mouse is not highlighted until the mouse is moved. (Desired behavior)

**Comment by taooceros** [comment] 2024-03-06 01:25
Your step 3 already change the selection. I wouldn't say we should reselect to the top result whenever reopen the window, which might be weird.

**Comment by Yusyuriv** [comment] 2024-03-06 02:44
> I wouldn't say we should reselect to the top result whenever reopen the window

If I understood correctly, they aren't asking to reselect the top result, but to ignore the mouse cursor when the window appear animation is in action. I also had this issue a few times. This issue only happens when the animations are enabled because Flow Launcher moves slightly up when it appears, triggering the selection with the mouse cursor. When animations are disabled this doesn't happen. The correct sequence of actions to reproduce this is:

0. Enable animations in the settings if they are disabled.
1. Open Flow Launcher.
2. Type something to populate the list.
3. Leave the first result selected, hit Esc to close the window.
4. Put the mouse cursor where the third result would be if the window was still open.
5. Open Flow Launcher with the shortcut. It appears and the animation of appearing triggers the selection of the result under the mouse.

**Comment by lotsocds** [comment] 2024-03-07 20:43
@taooceros Thanks for the reply.  This is a case where trying to make it easy to reproduce masked the real concern.  
@Yusyuriv You are correct regarding my issue.  Thank you for the corrected sequence of actions, and especially for the explanation why this happens.  I can certainly live without animation, so this request is resolved for me.  I will close it.

**Comment by Yusyuriv** [comment] 2024-03-07 20:46
I still think it's an issue that should be fixed. The user doesn't move the mouse, animation shouldn't trigger the selection with the mouse cursor.

**Comment by jjw24** [comment] 2024-03-08 10:19
Let's keep it open as it's a bug

**Comment by taooceros** [comment] 2024-03-08 16:44
I think we can add a small timeout whenever reshow the windows for the mousemove event.

**Comment by onesounds** [comment] 2024-05-03 23:45
I plan to delete the animation of the window moving.

There is one more similar issue. When the mouse is over the window, moving the list with the keyboard puts focus on the mouse cursor. (You can easily check this by holding down the down arrow key.) Something needs to be changed about mouse hover.

**Closed** 2024-05-17 05:52 UTC
Labels: bug
