### ISSUE TITLE
double-click ctrl

### ISSUE THREAD

**Issue by HardwayLinka** [Flow-Launcher/Flow.Launcher#1142] opened 2022-04-23 03:38 UTC
After using the Listary, i think that it's double-click ctrl launcher hotkey is convenient and easy to memorize, but setting double-click whatever key as launcher hotkey won't work on the Flow-Launcher.

**Comment by taooceros** [comment] 2022-04-23 04:08
duplicate of #954

**Comment by jjw24** [comment] 2022-04-24 06:29
Closing due to duplicate, feel free to join the discussion over there.

**Closed by jjw24** 2022-04-24 06:29 UTC
Labels: enhancement
