### ISSUE TITLE
BUG: Auto-scroll issue when selecting files in Flow Launcher

### ISSUE THREAD

**Issue by Adiversion** [Flow-Launcher/Flow.Launcher#3061] opened 2024-11-06 12:03 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When I search for files in Flow Launcher and there are more than three results, attempting to select the third file with the mouse causes the program to auto-scroll to the down or end. This prevents me from selecting the third file directly with my mouse.

### To Reproduce

1. Open Flow Launcher and search for files (more than three results should appear).
2. Try selecting the third result with the mouse.
3. Observe that Flow Launcher scrolls down to the last result, preventing selection of the third file.

### Screenshots

https://github.com/user-attachments/assets/4fd1f99e-fb76-41c9-9483-62dac75f1dff

Attaching videos for your reference

### Flow Launcher Version

1.19.4

### Windows Build Number

10.0.26100.2161

### Error Log

[2024-11-06.txt](https://github.com/user-attachments/files/17646725/2024-11-06.txt)

**Comment by z1nc0r3** [comment] 2024-11-06 12:48
Couldn't reproduce the issue. Does it keep scrolling until the last result on mouse hover?

Can you please try changing the `Settings > Apperanace > Maximum results shown` to a higher value?

**Comment by Adiversion** [comment] 2024-11-06 15:39
> Couldn't reproduce the issue. Does it keep scrolling until the last result on mouse hover?
> 
> Can you please try changing the `Settings > Apperanace > Maximum results shown` to a higher value?

No,  it doesn't scroll until last result 
It scrolls to 6-7 no. result

Thank you for you suggestion. I will do the same.

Is there any log i can reproduce for you help?

**Comment by z1nc0r3** [comment] 2024-11-06 16:46
You can get log files by typing "log" in FL. It will show the Logs dir and you can find it by date.
But I am not sure log files will help in this case though.

**Comment by Adiversion** [comment] 2024-11-07 05:46
I've uninstalled Flow Launcher, removed all related files from the Roaming folder, and reinstalled it, but the issue persists. When hovering the mouse towards the bottom of the list, it auto-scrolls, making it difficult to select items. Please see the attached video for reference.

https://github.com/user-attachments/assets/9f2beb3f-4ce3-4b6c-8b7e-415e7a76f153

**Comment by z1nc0r3** [comment] 2024-11-07 08:46
Interesting :/

Need to confirm a few things. 
- Is this on a Laptop or Desktop machine? If it is a Laptop please check the trackpad settings for scroll behavior.
- Is this behavior the same in other results also? Like programs, Google results, etc?

**Comment by Adiversion** [comment] 2024-11-07 09:12
> Interesting :/
> 
> Need to confirm a few things.
> 
> * Is this on a Laptop or Desktop machine? If it is a Laptop please check the trackpad settings for scroll behavior.
> * Is this behavior the same in other results also? Like programs, Google results, etc?

1. I am using a laptop.
2. Yes, the auto-scrolling behavior persists in other results as well.

**Comment by Adiversion** [comment] 2024-11-07 10:35
Update:

I created another user account on the same laptop, reinstalled Flow Launcher under that account, and it is now working properly. It seems the issue was related to Windows 11 24H2.

Thank you to everyone who helped me troubleshoot and resolve this issue. Please mark this bug as completed.

updated video for reference

https://github.com/user-attachments/assets/ff5acdc1-c736-4a3c-abc1-e16771a6e961

**Comment by z1nc0r3** [comment] 2024-11-07 20:04
Glad to hear that @Adiversion!

Since this worked properly on the new user account, it could mean that FL was affected by another third-party software. I noticed that the mouse pointer was different in the previous video clips. Is that just a mouse pointer scheme or some application?

I will close this for now. Please feel free to reopen it if needed.

**Closed by z1nc0r3** 2024-11-07 20:04 UTC
Labels: bug
