### ISSUE TITLE
   Allow to paste multiple lines.

### ISSUE THREAD

**Issue by thomasTAT** [Flow-Launcher/Flow.Launcher#2380] opened 2023-10-03 15:21 UTC
允许粘贴多行。   Allow to paste multiple lines.

Copy three lines, but paste only one line.
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/109513632/6c85624d-64f7-4c23-8845-c25b639bd42a)

**Comment by jjw24** [comment] 2023-10-03 18:57
Duplicate of #2039

**Closed by jjw24** 2023-10-03 18:57 UTC
Labels: enhancement
