### ISSUE TITLE
I can't launch Flow Launcher.

### ISSUE THREAD

**Issue by otaviokamel** [Flow-Launcher/Flow.Launcher#1929] opened 2023-02-23 16:53 UTC
I've tried reinstalling over and over, but Flow Launcher is giving the following error:

Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 02/23/2023 13:50:42
Exception:
System.NotSupportedException: 'Alt+LeftAlt' key and modifier combination is not supported for KeyGesture.
   at System.Windows.Input.KeyGesture..ctor(Key key, ModifierKeys modifiers, String displayString, Boolean validateGesture)
   at System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at Flow.Launcher.Converters.StringToKeyBindingConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\projects\flow-launcher\Flow.Launcher\Converters\StringToKeyBindingConverter.cs:line 15
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

It asked me to open a new issue here, copy the above message, and attach the following log.

[2023-02-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10816132/2023-02-23.txt)

**Comment by z1nc0r3** [comment] 2023-02-23 17:04
Duplicate of [#1755](https://github.com/Flow-Launcher/Flow.Launcher/issues/1755#issuecomment-1368983887)

**Closed by z1nc0r3** 2023-02-23 17:04 UTC
