### ISSUE TITLE
BUG: After recent update File explorer searches/lists aren't  showing up

### ISSUE THREAD

**Issue by a-y-a-n-das** [Flow-Launcher/Flow.Launcher#2535] opened 2024-02-05 06:59 UTC
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

After a recent update, I am not able to search files, docs, videos etc in flow launcher

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.17.0

### Windows Build Number

 10.0.22635.3139

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment] 2024-02-05 07:33
Dupe of #2530 . Fix on the way

**Closed by deefrawley** 2024-02-05 07:33 UTC
Labels: bug

**Comment by jjw24** [comment] 2024-02-05 10:34
Please update to 1.17.1

**Comment by a-y-a-n-das** [comment] 2024-02-05 11:05
Yehh! , Resolved.
