### ISSUE TITLE
FL shows duplicate entries in search results

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1194] opened 2022-05-08 19:08 UTC
**Describe the bug/issue**
FL shows duplicate entries in search results

**To Reproduce**
1. Created a copy of a pdf file and renamed it with a unique name
2. Searched for this unique name using FL
3. FL listed two identical entries

**Screenshots**
![image](https://user-images.githubusercontent.com/9047168/167311770-56b59ef2-40d9-47d8-9285-329bc90f39c7.png)
**Your System**
Windows 10 Home 64 bit
Version: 10.0.19044 Build 19044

Flow Launcher version: (Settings => About) 
1.10.0 portable

**Flow Launcher Error Log**
I am unable to see logs subfolder at this location!

**Comment by deefrawley** [comment] 2022-05-09 02:19
As per the previous issue, this is most likely Explorer and Everything showing you the same result. Disable one (or add a keyword) and try again and let us know if this is what the issue is.

**Comment by raindropsfromsky** [comment] 2022-05-09 07:15
Oh ok.

Could you kindly elaborate differences between these plugins, so that the user can select the right plugin he needs?
If any of them has additional features that are not available in the other, then I would want both!

**Comment by jjw24** [comment] 2022-05-09 22:04
Explorer plugin uses Windows Search (otherwise also know as Windows Indexing), which is Windows' own indexing service. Everything plugin uses its own indexing service. The main difference here is you may need to do a bit of configuration of the Windows indexing options to ensure that certain directories you need will be indexed where as Everything's indexing I think covers all folders on the hard drive. This also means some laptops that have Windows Search disabled, will not be able to use Explorer to search for files and folders directly, this is where Everything comes in.

Personally I don't like installing and running an additional process in the background being Everything's indexing service which takes up some more memory so I use Explorer which just uses Window's service that is already running. The downside with Explorer however is that configuring Windows Search can be a bit fiddly to get right.

Everything plugin does not traverse folders but opens them in Windows explorer directly like Explorer plugin, and does not allow you to favourite your frequently used directories and files. 

These differences will be addressed in the future as we already have a draft PR to merge the two plugins together so you get the best of both worlds with just one plugin, however this may be not be completed in the immediate short term.

**Comment by jjw24** [comment] 2022-05-09 22:18
If you are not already familiar with Everything software, then give Explorer plugin a go. There are issues posted around how to configure the Windows Search if you run into problems and you can always ask us as well.

**Comment by raindropsfromsky** [comment] 2022-06-07 06:33
Sorry for the delayed response, but I just noticed that a **_"waiting for response"_** tag is attached to this issue.
Should I be providing some response?

Personally, I opted to continue using both plugins, because it's not a big problem to have duplicate entries.
I'd rather have false positives as compared to missing some results!

**Comment by jjw24** [comment] 2022-06-10 22:46
Hey thanks for responding and letting us know, will follow the issue now.

**Closed by jjw24** 2022-06-10 22:46 UTC
Labels: question/discussion, Waiting for response
