### ISSUE TITLE
Option to set it as the windows startup search

### ISSUE THREAD

**Issue by DannyDarth** [Flow-Launcher/Flow.Launcher#2240] opened 2023-07-11 12:59 UTC
**Is your feature request related to a problem? Please describe.**
Not that i am aware.

I normal use the win key and type something in to search the web. I use to use edgeredirect to mozilla to search in the windows search bar from the start menu, now that i have removed edge ive come to this program.

**Describe the solution you'd like**
When you bring up the start menu and type to search for something, have it default to flow launcher.

so if i press the windows key or even just click the start menu and type something to search in. Have it use flow launcher.

**Describe alternatives you've considered**
I'm not sure there is any.

Im not sure of any.

**Additional context**

make it use this search bar:

https://i.imgur.com/kHBTD7x.png

**Comment by JohnTheGr8** [comment] 2023-07-11 13:12
#662

**Comment by jjw24** [comment] 2023-07-11 13:19
Hi there, this sounds like a duplicate of issue 662. Please follow that issue for future updates.

**Closed by jjw24** 2023-07-11 13:19 UTC
Labels: enhancement
