### ISSUE TITLE
Hotkey display incorrect when using WebSearch global wildcard

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#43] opened 2020-05-08 10:13 UTC
Set WebSearch google search hotkey from default 'g' to '*'

search 'YouTube hello'

![image](https://user-images.githubusercontent.com/26427004/81396137-2fa21880-9168-11ea-8971-d51e70f5510e.png)

**Comment by deefrawley** [comment] 2023-03-03 22:46
I can't reproduce this in any plugin so assuming this has been fixed in subsequent updates

**Closed by deefrawley** 2023-03-03 22:46 UTC
Labels: bug, kind/ui
