### ISSUE TITLE
[Dev] changing the priority of plugin sometimes cause the plugin page unrespond

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#756] opened 2021-10-15 21:03 UTC
not sure how to consistently reproduce the issue, but have experienced it for a couple of times.

**Comment by jjw24** [comment] 2022-07-08 11:04
I actually experienced this when I change hotkey, but also not consistently reproducible.

**Comment by jjw24** [comment] 2022-12-04 18:57
Closing. Let's reopen when it happens again since this is from Oct 2021

**Closed by jjw24** 2022-12-04 18:57 UTC
Labels: bug
