### ISSUE TITLE
Error Loading All Plugins

### ISSUE THREAD

**Issue by robertoleonardo** [Flow-Launcher/Flow.Launcher#95] opened 2020-06-30 07:56 UTC
Yes

- 

I am switching to Flow from Wox, but I can't seem to get any third party plugins to load on restart after a successful installation message.  Is that just how it is for now, with flow in this early stage, or should they be working?  I've tried installing--in flow--numerous of the plugins i use in wox and upon restarting the application i get a plugin load error for each and every plugin.

Apologies if i'm dumb and the plugins aren't supposed to work just because they haven't been modified to work on flow, but the content on github here suggests they should be working even now.  

ERROR MESSAGE (using spotify as an example, but i've tried numerous plugins and none work):  "The following plugin has errored and cannot be loaded....Wox.Spotify Premium...Please refer to the logs for more information"

LOG FILE: 

[2020-06-30.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/4850218/2020-06-30.txt)

SCREENSHOT:

![Snag_1b31d48](https://user-images.githubusercontent.com/13153043/86099402-4aa84f00-ba6c-11ea-91fa-28da97074fa1.png)

**Comment by jjw24** [comment] 2020-06-30 08:47
Hey how's it going. We are still working on integrating with Wox plugins, currently Wox plugins are still erroring out. What's some of the plugins that you would like to use, I can see if I am able to update them to Flow Plugins for now.

**Comment by robertoleonardo** [comment] 2020-06-30 09:05
Ah - thank you! i figured that was likely to be the explanation. please take your time and don't go out of your way to prioritize my preferences, but the only three i use other than the built ins are:
1) wox.processkiller
2) wox.spotifypremium
3) google search plus

Thank you all for your work on this - it's making my work life a lot easier. and the windows search/environmental variables search is HUGE. i appreciate you.


________________________________

**Comment by JohnTheGr8** [comment] 2020-06-30 12:59
I was thinking that the process-killer plugin could be one of the defaults, @jjw24 what do you think?

**Comment by robertoleonardo** [comment] 2020-06-30 15:51
Agree - I have always thought it kind of odd that it wasn't


________________________________

**Comment by theClueless** [comment] 2020-06-30 19:02
@jjw24 @JohnTheGr8 In the past I took process killer plugin and made some updates and upgrades to it (much faster and doesn't crush as much).
It was in a private repo until now but maybe you could use it as a baseline :)
https://github.com/theClueless/Wox.Plugins

**Comment by JohnTheGr8** [comment] 2020-06-30 20:52
@theClueless thanks for pointing this out, I'll try to find some time to ~~steal~~ port it tomorrow.

**Comment by DonKonfetti** [comment] 2020-07-02 19:20
I'd love to see the task killer functionality in Flow, too. I used it very often back in Wox days.

And btw, awesome work @jjw24 ! Really wish I had more spare time to join.

**Comment by jjw24** [comment] 2020-07-02 20:31
> I'd love to see the task killer functionality in Flow, too. I used it very often back in Wox days.
> 
> And btw, awesome work @jjw24 ! Really wish I had more spare time to join.

Thanks @DonKonfetti, the @Flow-Launcher/team is the reason Flow is able to move forward this far.

@JohnTheGr8 is working on adding task killer plugin into Flow. Stayed tuned.

**Comment by gundamhyl** [comment] 2020-07-21 12:39
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|-------------------------- Begin exception --------------------------
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|The GetTypes method was unable to load assembly types for the plugin: <Dictionary>
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|Exception full name:
 <System.Reflection.ReflectionTypeLoadException>
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|Exception message:
 <Unable to load one or more of the requested types.
Could not load file or assembly 'Wox.Plugin, Version=1.3.159.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.>
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|Exception stack trace:
 <   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Flow.Launcher.Core.Plugin.PluginsLoader.<>c__DisplayClass4_1.<DotNetPlugins>b__1() in C:\Workbench\Git\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 56>
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|Exception source:
 <System.Private.CoreLib>
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|Exception target site:
 <System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)>
2020-07-21 20:26:50.8998|ERROR|PluginsLoader.DotNetPlugins|Exception HResult:
 <-2146232830>


problem in https://github.com/harrynull/WoxDictionary

**Comment by gundamhyl** [comment] 2020-07-22 13:56
@jjw24

**Comment by jjw24** [comment] 2020-07-22 20:11
> @jjw24 

Hey how's it going. This would be due to it being Wox plugin. I will work on porting the plugins mentioned here and then you guys will be able to download and add them manually into flow for now. We are still in the process of setting up automatic integration after porting.

**Comment by jjw24** [comment] 2020-08-18 22:57
Hey @gundamhyl , I have ported WoxDictionary to Flow, please test it out and let me know if it is working as intended.
https://github.com/jjw24/WoxDictionary/releases/latest

**Comment by jjw24** [comment] 2020-08-19 04:46
Hey @robertoleonardo , Google Search Plus has been ported. Please test it out and let me know how you go.
https://github.com/jjw24/Wox.Plugin.GoogleSearch/releases/latest

**Comment by gundamhyl** [comment] 2020-08-19 14:06
> Hey @gundamhyl , I have ported WoxDictionary to Flow, please test it out and let me know if it is working as intended.
> https://github.com/jjw24/WoxDictionary/releases/latest

Thanks! This plugin works well now, but did you solve this problem by recompiling it? Does every wox version of the plugin need to be modified before it can be installed in Flow.Launcher? Is there any other way to be compatible with the old version of the plugin?

**Comment by jjw24** [comment] 2020-08-19 21:00
> Thanks! This plugin works well now, but did you solve this problem by recompiling it? 
Nah it wasnt a compile issue, I upgraded the plugin to .Net Core and changed the plugin interface to Flow's.

> Does every wox version of the plugin need to be modified before it can be installed in Flow.Launcher? Is there any other way to be compatible with the old version of the plugin?
Yeah, at this stage all Wox version of the plugin need to be ported before it can be installed in Flow Launcher. The benefits will be that a lot of the plugins that I have come across so far are built years ago, so code base is pretty out of date. Porting them over will help with knowing what state these plugins are in, and also upgrading to the most recent stable framework so they can be developed further/ have their issues fixed.

**Comment by jeremymeyers** [comment] 2020-10-13 03:21
Please also these:

-  Discogs **http://www.wox.one/plugin/90** 
-  SwiftTweet http://www.wox.one/plugin/63
-   Todoist http://www.wox.one/plugin/292
- Timer https://github.com/creativitRy/WoxTimer
- Graphical Timer https://github.com/JaroslawPokropinski/Wox.Plugin.GraphicalTimer

**Comment by jjw24** [comment] 2020-10-13 08:34
> Please also these:
> 
> * Discogs **http://www.wox.one/plugin/90**
> * SwiftTweet http://www.wox.one/plugin/63
> * Todoist http://www.wox.one/plugin/292
> * Timer https://github.com/creativitRy/WoxTimer
> * Graphical Timer https://github.com/JaroslawPokropinski/Wox.Plugin.GraphicalTimer

hey no problem, I have created a dedicated issue to capture these plugin port requests. 

Will be closing this issue and future requests please see the issue referenced above.

**Closed by jjw24** 2020-10-13 08:34 UTC
Labels: bug, plugin/port
