### ISSUE TITLE
BUG: Plugin settings empty

### ISSUE THREAD

**Issue by Gh0stExp10it** [Flow-Launcher/Flow.Launcher#2819] opened 2024-07-04 12:12 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

As already described in Issue #2531 and the comments, the plugin settings are often empty. Default values in particular are only displayed after a fresh installation of the plugin. When closing and reopening the settings, the Plugin settings are empty.  The settings values are only displayed as soon as the keyword is triggered in the Flow-Launcher.

Plugin for example "HA-Commander".

I'm using the latest [v1.18.0](https://github.com/Flow-Launcher/Flow.Launcher/releases/tag/v1.18.0).

### To Reproduce

1. Open Flow-Launcher settings
2. Head to menu "Plugins"
3. Click on a Plugin with custom settings (SettingsTemplate)
4. Defaults are empty, no input was given by the user yet (please see below screenshot)

### Screenshots

![Screenshot_2024-07-04](https://github.com/Flow-Launcher/Flow.Launcher/assets/7295005/67933518-d20b-4e77-a672-9c4c2360bde2)

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22631.3810

**Comment by Yusyuriv** [comment] 2024-07-04 12:19
I think #2577 is the same issue.

**Comment by Gh0stExp10it** [comment] 2024-07-04 12:23
> I think #2577 is the same issue.

Yes, you are right. Didn't saw that in my search. How to handle? close duplicates and only mentioned in your issue report?

**Comment by Yusyuriv** [comment] 2024-07-04 20:59
Yep. Thank you for the bug report though, we appreciate that 🙂

Closed as duplicate of #2577

**Closed by Yusyuriv** 2024-07-04 20:59 UTC
Labels: bug
