### ISSUE TITLE
BUG: Plugin store not updating in a timely manner when a new plugin ver released

### ISSUE THREAD

**Issue by deefrawley** [Flow-Launcher/Flow.Launcher#2048] opened 2023-04-13 00:23 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I updated General Converter to v2.0 over 12 hours ago. Plugin manifest picked up the changes shortrly after, but Flow Plugin Store hasn't updated and shows version 1.4 still

Using `pm install` installs v1.4

Tried reinstalling Flow, and hitting Refresh in the Plugin Store but no update.

This must update eventually otherwise there would be no plugin updates since the last change, but it should be much quicker than this.

### Flow Launcher Version

1.14.0

### Windows Build Number

Microsoft Windows [Version 10.0.19045.2846]

### Error Log

Log shows that a manifest update occurred:

`09:56:51.9743+10:00 - INFO  - PluginsManifest.UpdateManifestAsync - Fetched plugins from manifest repo`

**Comment by JohnTheGr8** [comment] 2023-06-02 11:52
I also noticed this today and had a look... it's caused by the CDN we use in [PluginsManifest.cs#L15](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs#L15). jsDelivr caches for 12 hours.

We can switch back to a direct Github link, but Chinese users will have issues 🤷‍♂️

**Comment by jjw24** [comment] 2023-06-02 11:55
Good pick up @JohnTheGr8. I don't suppose there is any settings with it we can tweak to reduce the cache time?

**Comment by JohnTheGr8** [comment] 2023-06-02 12:04
they offer a limited-access API for purging cache that we _could_ use from the CI script... but it shouldn't be worth the trouble.

Maybe we should use a Github link by default and either:
* fall back to jsdelivr if the github link fails
* make the manifest URL configurable from settings

**Comment by jjw24** [comment] 2023-06-02 12:22
> they offer a limited-access API for purging cache that we _could_ use from the CI script... but it shouldn't be worth the trouble.
> 
> Maybe we should use a Github link by default and either:
> 
> * fall back to jsdelivr if the github link fails
> * make the manifest URL configurable from settings
> * or both of the above

This might be our last resort.

If It's a simple API call to purge, we can do that after the manifest is updated.

@taooceros do you know any other viable CDN options?

**Comment by JohnTheGr8** [comment] 2023-06-02 13:30
> This might be our last resort.

keep in mind that their docs state:

> To avoid abuse, access to purge is given after an email request (for now - [dak@prospectone.io](mailto:dak@prospectone.io)).

**Comment by JohnTheGr8** [comment] 2023-06-05 16:56
btw I tried their [online purge tool](https://www.jsdelivr.com/tools/purge) the other day and, while it said it succeeded, the purge didn't propagate correctly for me (they use a combination of cloudflare, fastly and gcore for CDN). 

Testing through a server in another country I got an up-to-date response, but from my location I was getting outdated content for a few more hours... 😢

**Comment by jjw24** [comment] 2023-06-07 08:29
OK, so the purge tool doesn't sound reliable enough.

>Other CDNs will also cache for a few hours ;)

I haven't played much with CDNs in general, anyone else have any input? @Flow-Launcher/team

**Comment by JohnTheGr8** [comment] 2023-06-07 16:33
To elaborate a bit further, a user-configurable manifest URL (like an option between github, jsdelivr or user-defined) would also have the following additional benefits:
1. it will be possible to have "unofficial" plugin communities, which means the whole ecosystem is a bit more open
2. it will make it possible to do full integration testing of plugins: for example, before opening a PR to the manifest repository to add a new plugin, I can point my flow-launcher to my fork repository and test that a complete install/update/etc works as expected...

I understand this is not necessary at this point, we can leave that for later... ;)

**Comment by jjw24** [comment] 2023-06-09 02:56
I have been wanting to enable this since day 1 :+1: will create an issue.

**Comment by jjw24** [comment] 2023-06-09 03:06
> they offer a limited-access API for purging cache that we _could_ use from the CI script... but it shouldn't be worth the trouble.
> 
> Maybe we should use a Github link by default and either:
> 
> * fall back to jsdelivr if the github link fails
> * make the manifest URL configurable from settings
> * or both of the above

Let's go with this solution:
- use GitHub link by default
- fall back to jsdelivr
- for now just keep the links in settings file, no ui needed. Keep scope small and also future will be expanded for issue 2178.

**Comment by JohnTheGr8** [comment] 2023-06-11 11:42
Is there a point in fetching the manifest file from a CDN (initially to make it work from China) when the actual plugin files are still being fetched from github.com? 😆

**Comment by jjw24** [comment] 2023-06-11 12:30
Is this existing code you are asking?

I think you can just fetch from GitHub and if that fails then fetch from CDN.

**Comment by JohnTheGr8** [comment] 2023-06-11 12:37
> Is this existing code you are asking?
> 
> I think you can just fetch from GitHub and if that fails then fetch from CDN.

I'm talking about existing code, yes. 

We use jsDelivr to fetch the `plugins.json` file so that it works from China... but the plugin download links (the `UrlDownload` fields) inside it are all `github.com` links.

We could translate github.com links in the `UrlDownload` field to CDN links, but I can't get it to work... When using [jsdelivr's tool](https://www.jsdelivr.com/github) I am getting invalid links.

**Comment by deefrawley** [comment] 2023-06-11 22:48
> Is there a point in fetching the manifest file from a CDN (initially to make it work from China) when the actual plugin files are still being fetched from github.com? 😆

If the code has always been this way, and we don't have any issues from Chinese users about not being able to download plugins, then do we even have a problem we need jsDelivr to solve?

**Comment by jjw24** [comment] 2023-06-13 12:15
>We could translate github.com links in the UrlDownload field to CDN links, but I can't get it to work... When using [jsdelivr's tool](https://www.jsdelivr.com/github) I am getting invalid links.

This is not supported and probably won't be any time soon https://github.com/jsdelivr/jsdelivr/issues/18203

>We use jsDelivr to fetch the plugins.json file so that it works from China... but the plugin download links (the UrlDownload fields) inside it are all github.com links.

Oh sorry I didn't make the connection, ok got what you mean.

>then it's only for performance, which is not significant since the plugins.json file is very small and we use conditional requests to make repeat loads fast...
@jjw24 should we just change to a github link for now then?

If we change to GitHub link wouldn't the Plugin Store load very slowly or not at all for Chinese users?

If we are not having any issues from Chinese users about not being able to download plugins, i.e. current setup is at least acceptable. Maybe we should keep how the setup is currently, so connect directly to GitHub for the manifest file if that fails then just switch to current jsdelivr's url ?

**Comment by JohnTheGr8** [comment] 2023-06-13 13:26
> If we change to GitHub link wouldn't the Plugin Store load very slowly or not at all for Chinese users?

Maybe, but I think it's pointless to keep using a CDN link to a tiny file (84 KB) when it is causing other issues, only for the speed benefits. Plugins and app updates (which are 90 MB) are still fetched from Github.

I personally don't recall anybody complaining about plugin store load times being bad from China...

In my opinion, if we are going to make the manifest URLs user-configurable in the future for #2178, then it makes sense to keep things simple at this stage and only update the current link to github.com

> This is not supported and probably won't be any time soon [jsdelivr/jsdelivr#18203](https://github.com/jsdelivr/jsdelivr/issues/18203)

Good find, weird that their tool just gives you a broken link...

**Comment by jjw24** [comment] 2023-06-13 13:48
My only concern with switching back the manifest URL to GitHub is causing issues like theee #1162. IIRC we haven't had one of these issues after the use of CDN, and I don't quite know why actual plugin downloads and app updates don't cause issues, maybe they just wait for the download even though it's slower?

**Comment by jjw24** [comment] 2023-08-16 12:17
This is addressed in the recent release.

**Closed by jjw24** 2023-08-16 12:17 UTC
Labels: bug, keep-fresh
