### ISSUE TITLE
got a bug

### ISSUE THREAD

**Issue by Hemantsingh4774** [Flow-Launcher/Flow.Launcher#1120] opened 2022-04-10 07:46 UTC
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True
[2022-04-10.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8458527/2022-04-10.txt)

Python Path: 
Date: 04/10/2022 13:04:09
Exception:
System.AggregateException: One or more errors occurred. (No process is associated with this object.)
 ---> System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass26_0.<ExecuteAsync>b__0() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 263
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment] 2022-04-10 11:57
https://ci.appveyor.com/api/buildjobs/trey45b52i14mxx3/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe
try this build?

**Comment by taooceros** [comment] 2022-04-10 11:57
Duplicate of #988

**Comment by jjw24** [comment] 2022-05-28 05:15
See issue 988 for fix progress.

**Closed by jjw24** 2022-05-28 05:15 UTC
Labels: Waiting for response

**Comment by Hemantsingh4774** [comment] 2022-05-28 15:00
okay

**Comment by jjw24** [comment] 2022-05-30 23:18
Hey @Hemantsingh4774, does this build resolve your issue?
https://github.com/Flow-Launcher/Flow.Launcher/issues/1120#issuecomment-1094255701
