### ISSUE TITLE
Flow Launcger got an error

### ISSUE THREAD

**Issue by HBenzaoui** [Flow-Launcher/Flow.Launcher#1228] opened 2022-06-04 09:27 UTC
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 06/04/2022 10:25:52
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.MainViewModel.RemoveOldQueryResults(Query query) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 632
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-06-04.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8837366/2022-06-04.txt)

**Comment by taooceros** [comment] 2022-06-04 12:43
duplicate of #1067

**Comment by jjw24** [comment] 2022-06-04 13:07
Please track issue 1067 for fix progress.

**Closed by jjw24** 2022-06-04 13:07 UTC
