### ISSUE TITLE
Put the executable path into the quote 

### ISSUE THREAD

**Issue by hahaleyile** [Flow-Launcher/Flow.Launcher#2000] opened 2023-03-22 03:46 UTC
https://github.com/Flow-Launcher/Flow.Launcher/blob/bcc29ce3c14b935cab07d51ddb51f06f415015fe/Flow.Launcher/Helper/AutoStartup.cs#LL54C67-L54C67

The auto startup path needs to be in a quote, otherwise it will not be able to start.

![image](https://user-images.githubusercontent.com/38727644/226797050-46fc953c-bb6f-436a-8157-4259d7a964bf.png)

**Comment by deefrawley** [comment] 2023-03-22 05:12
Not true (also auto starting for users just fine).
Closing issue. If you have a specific issue with your installation not doing this feel free to re-open and we can troubleshoot with you.

**Comment by hahaleyile** [comment] 2023-03-22 12:51
You are right, other problem cause this issue. Here is the log:

[2023-03-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11040069/2023-03-22.txt)

**Comment by jjw24** [comment] 2023-03-22 21:43
Hi @hahaleyile how's it going? Is the issue that your flow is not starting?

**Comment by deefrawley** [comment] 2023-03-23 00:46
This is odd

`20:47:49.4073+08:00 - WARN  - PluginConfig.GetUniqueLatestPluginMetadata - Duplicate plugin name: Currency Converter, id: 18892b78-63ac-43ab-a278-59a5a2866dd8, version: 2.0.3 not loaded due to version not the highest of the duplicates`

Not sure if it is the cause of wider issues but could you uninstall the plugin and then reinstall it?

**Comment by jjw24** [comment] 2023-03-23 02:07
This is where there are two of the same plugins, navigate to folders user data -> plugins and remove the duplicates until one is left, then start flow.

**Comment by hahaleyile** [comment] 2023-03-23 05:54
Things go as you said, there are two of the same plugins. But when I delete all of theme, I still can't make auto startup happen. Here is the log:

[2023-03-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11047400/2023-03-23.txt)

I notice that auto startup doesn't produce log file, this is the log file when I manually start program.

**Closed** 2023-06-17 13:33 UTC
