### ISSUE TITLE
priority in windows settings plugin

### ISSUE THREAD

**Issue by ourslfs** [Flow-Launcher/Flow.Launcher#886] opened 2021-12-09 15:11 UTC
**Is your feature request related to a problem? Please describe.**

After update I noticed that windows settings elements are higher in priority than control panel elements which is kind of very inconvenient sometimes

**Describe the solution you'd like**

Maybe add option in that plugin to priorities control panel elements pls

**Comment by skjerns** [comment] 2021-12-14 08:47
I realized this problem as well!

**Comment by jjw24** [comment] 2022-02-28 20:22
Duplicate of #1008 

This is fixed and merged into the pre-release which you can download the [portable version](https://ci.appveyor.com/api/buildjobs/aa4uamuq3k3wtp1o/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip)

**Closed** 2022-02-28 20:23 UTC
Labels: enhancement
