### ISSUE TITLE
Shell plugin "WIN+R" hotkey cursor default position error

### ISSUE THREAD

**Issue by duzp** [Flow-Launcher/Flow.Launcher#1025] opened 2022-02-13 09:33 UTC
use WIN+R hotkey launch input box, default curosr position is at the front. 
If you want to run the command, you need to move the cursor to after the ">" character
![image](https://user-images.githubusercontent.com/26558646/153747113-a11fbd9b-2254-4ccb-9365-9c735f5d2194.png)

**Comment by taooceros** [comment] 2022-02-13 20:27
Could you try restarting flow? I cannot reproduce the bug.

**Comment by duzp** [comment] 2022-02-14 02:25
> Could you try restarting flow? I cannot reproduce the bug.

I've tried restarting the computer and software, but it still doesn't work

**Comment by duzp** [comment] 2022-02-14 04:39
I don't know why, it‘s working fine now..

**Comment by taooceros** [comment] 2022-02-14 04:43
> I don't know why, it‘s working fine now..

lol 🤣 If you can reproduce the bug consistently, we can resolve it. But now, probably we can just leave it like this.🤣

**Comment by jjw24** [comment] 2022-02-17 06:57
Closing. Feel free to reopen if happens again.

**Comment by bogdamel** [comment] 2022-02-28 14:39
I have a similar bug but it's not only CMD. When I use custom shortcuts (e.g. Alt+S, Alt+F, Alt+G, Alt+Q) the cursor is not in the right place. 

![28 02 2022 16-30](https://user-images.githubusercontent.com/24360830/156001214-85f7556e-8a79-47e5-a125-5effec6b2a27.gif)

**Comment by taooceros** [comment] 2022-02-28 14:48
> I have a similar bug but it's not only CMD. When I use custom shortcuts (e.g. Alt+S, Alt+F, Alt+G, Alt+Q) the cursor is not in the right place. 
> 
> ![28 02 2022 16-30](https://user-images.githubusercontent.com/24360830/156001214-85f7556e-8a79-47e5-a125-5effec6b2a27.gif)
> 

Would you please share the log? Find it via "open log location".

**Comment by bogdamel** [comment] 2022-02-28 14:51
Here they are.

[2022-02-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8154198/2022-02-27.txt)
[2022-02-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8154200/2022-02-28.txt)

**Comment by bogdamel** [comment] 2022-02-28 19:11
> I have a similar bug but it's not only CMD. When I use custom shortcuts (e.g. Alt+S, Alt+F, Alt+G, Alt+Q) the cursor is not in the right place.
> 
> ![28 02 2022 16-30](https://user-images.githubusercontent.com/24360830/156001214-85f7556e-8a79-47e5-a125-5effec6b2a27.gif)

Another scenario for this problem to occur. It appears after opening a context menu by either pressing the right arrow button or doing a left mouse click and then returning to the results menu.

![28 02 2022 20-59](https://user-images.githubusercontent.com/24360830/156042524-ccb99db2-e03d-4dd6-a537-9a8a4809ed77.gif)
 
Log files if you need them:
[2022-02-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8156004/2022-02-27.txt)
[2022-02-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8156005/2022-02-28.txt)

**Comment by duzp** [comment] 2022-03-01 03:07
> I don't know why, it‘s working fine now..

on my computer, the bug appeared again🤣.with this bug, the first time I press the shortcut key(WIN+R) and run any command, then press the shortcut key for the second time, Flow won't respond, Windows will pop up the RUN window.
![FlowLauncher](https://user-images.githubusercontent.com/26558646/156097332-8bc5d130-6d7d-4e2a-af2c-6ba4bf6fc21c.gif)

**Comment by medlir** [comment] 2022-03-03 17:08
This has been bugging me for a while now too, was hoping it was fixed in 1.9.3 today but it's not.  It was fixed briefly in b0a86ce4a5 , but then stopped working again a couple versions ago, I assume it broke for a different reason though this time, during the plugins rewrites.  I assume somewhere in the Shell plugin in OnWinRPressed() it needs to possibly set the main window QueryTextCursorMovedToEnd so the main window triggers the call to MoveQueryTextToEnd(); but I'm not overly proficient in C#, or how this view model works, or what's possible to do from the Shell plugin... other than I noticed that QueryTextCursorMovedToEnd seems to be a public bool getter/setter while MoveQueryTextToEnd is private, so seemed like at least a possibility.  I may try to stumble through it myself with trial and error in a bit, if it's not too time-consuming to setup the build env.

**Comment by taooceros** [comment] 2022-03-03 17:18
Hi, it will be awesome if you can setup the dev env. I personally cannot reproduce the same bug, so it will be valuable if you can debug yourselves. 

Hard to say whether it is easy or hard, but at least you may need to install the dotnet 5/6 env (I remember they have backward compatibility so 6 may be good), and a debugger.

If you don't mind the large visual studio size, you can just directly install that and don't worry so much about the env.

**Comment by taooceros** [comment] 2022-03-03 17:19
> it needs to possibly set the main window QueryTextCursorMovedToEnd so the main window triggers the call to MoveQueryTextToEnd();

This should have been done within the ChangQuery.

**Comment by taooceros** [comment] 2022-03-12 03:45
Try this build https://ci.appveyor.com/api/buildjobs/x8hiob8qxh39jy7k/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe

**Comment by BetterYoung** [comment] 2022-03-19 04:29
I find a clue：
if set "Last Query Style" = "Empty last query", the cursor default position will behind '>'
![image](https://user-images.githubusercontent.com/27729842/159106720-da9a767f-824f-4c2a-8db8-23b813ea376b.png)

![image](https://user-images.githubusercontent.com/27729842/159106750-cbe6bc60-393d-4d9a-835c-536dc0ab03b4.png)


> > I don't know why, it‘s working fine now..
> 
> lol 🤣 If you can reproduce the bug consistently, we can resolve it. But now, probably we can just leave it like this.🤣

**Closed** 2022-06-28 13:41 UTC
Labels: bug
