### ISSUE TITLE
WebSearch 1.3.2 -  Action keywords collisions with default configurations

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#432] opened 2021-05-18 05:05 UTC
**To Reproduce**
1. Use portable version of Flow Launcher (this is optional, but helps with testing on a clean install)
2. Delete all of the default search entries like Wiki or Bing 
3. Close the app completely (optional)
4. Open the app  and try to add Bing back.

Note in this pic, Bing does not exist
![image](https://user-images.githubusercontent.com/1836362/118593049-e3ff5300-b75b-11eb-940e-169db2b1199e.png)

When I tried to add Bing back (using my URL configuration), it alerted of name collision.  If I used "bing" instead of "b" it allows me to save.
![image](https://user-images.githubusercontent.com/1836362/118592648-25dbc980-b75b-11eb-8fcb-a187a74b814d.png)

Windows 10 64bit LTSC
![image](https://user-images.githubusercontent.com/1836362/118592684-35f3a900-b75b-11eb-8564-d62b72145bc4.png)

WebSearch 1.3.2. 
Flow Launcher 1.7.2

**Flow Launcher Error Log** 

** ** NOTE** ** I cleared all logs file, reproduced the error, and copied the log file. There's no mention in the log of the action collision.

**Comment by taooceros** [comment] 2021-05-18 12:39
It seems that that's because the browser favorites plugin is holding the action keyword "b" so you are unable to set the keyword of bing search to that.

**Comment by taooceros** [comment] 2021-05-19 04:53
@mochigithub how's going?

**Comment by mochigithub** [comment] 2021-05-19 06:27
> @mochigithub how's going? I think using another actionkeyword will work fine.

Yes, another keyword works fine, but this is non-standard design.  If an entry is deleted, it should be deleted with the action keyword associated it.  Just because it was there by default doesn't mean the app should still steal/keep the keyword. Does that make sense? 

What is  the "browser favorites plugin"?  Do you mean browser bookmarks plugin?

**Comment by mochigithub** [comment] 2021-05-19 07:19
Came back to write this -- this is definitely a bug.  Once the user deletes the default entry, there's no way I can find to restore the default action word--- they're lost forever!   For example, I lost "b" because I deleted the Bing default and re-added after.

**Comment by taooceros** [comment] 2021-05-19 08:04
But the default actionkeyword for Bing is "bing".... If you would like to use b for bing, change the actionkeyword of the browserbookmark plugin. We don't support duplicate actionkeyword for now.

**Comment by mochigithub** [comment] 2021-05-19 09:51
Ohhhhhhh @taooceros  I understand what you meant now by b for bing.  The plugin itself is tying itself to the search plugin.  
I changed the bookmark one to br and changed bing to B. That explains bing, but what about Wiki??

![image](https://user-images.githubusercontent.com/1836362/118792874-ec838680-b84c-11eb-951f-3821c820c6a6.png)

There is **no other** entry for **wiki** action keyword, yet it's still preventing me from assigning that action.
![image](https://user-images.githubusercontent.com/1836362/118793040-12a92680-b84d-11eb-935e-560e8a3f63b0.png)

**Comment by taooceros** [comment] 2021-05-19 09:55
Hmmm I will take a look on whether it has deleted the action keyword successfully.

**Comment by mochigithub** [comment] 2021-05-19 09:55
> Hmmm I will take a look on whether it has deleted the action keyword successfully.

Thank you!!! I think that's what's going on here.  The keywords are not deleting successfully and are actually still hidden in the background.

**Comment by taooceros** [comment] 2021-05-21 09:01
I didn't find a logic issue in edit and delete actionkeyword in code. I do have tried to remove the entry and readd it, and it works fine.

**Comment by taooceros** [comment] 2021-05-21 09:04
There is one issue that can prevent you doing this is to only copy the setting from websearch plugin but without the plugin.json, which contains the actionkeyword registered information. Therefore, it will create the issue for unable to add entry. I think this is also the reason of #442. Would you please also copy the plugin.json to websearch plugin directory, or manually edit the actionkeywords property in plugin.json.

The directory should lies within %localappdata%\FlowLauncher\app-1.7.2\Plugins\Flow.Launcher.Plugin.WebSearch\

**Comment by taooceros** [comment] 2021-05-21 17:32
Sorry I think what I states before is not correct. The actual action keywords will be stored within the Setting.json under the setting folder. To modify that may require you to modify a specific property lies within it. Hmmm let me provide that information tomorrow.

**Comment by taooceros** [comment] 2021-05-22 01:47
C:\Users\1\AppData\Roaming\FlowLauncher\Settings\Settings.json

![image](https://user-images.githubusercontent.com/45326534/119210956-f5d95100-bae1-11eb-8753-904d2884ca03.png)

Find this part in the setting and modify the actionkeyword after closing Flow (to avoid saving) to the actionkeywords listed in the other computer to allow flow to reassign actionkeyword. This is because the actionkeyword settings and the plugin system are separated, so the Websearch plugin won't try to load actionkeyword from its setting.

**Comment by jjw24** [comment] 2021-05-25 03:08
@mochigithub did we get to the bottom of this issue?

**Comment by mochigithub** [comment] 2021-05-25 05:05
Yes. It's not the end of the world since one can always work around it but I appreciate all of the time you put into this!

**Comment by jjw24** [comment] 2021-05-25 09:17
hey @mochigithub @taooceros I think I know what's going on. I was able to fully reproduce the bug @mochigithub experienced following the steps in the issue description, and yes getting the same plugin action keyword is in use. I replicated this error with current latest release 1.7.2, but could not replicate it anymore with the 1.8.0 release in the pipeline. @taooceros you must have been looking at the dev branch code?

Anyway we may have fixed this bug along the way to 1.8.0, so when this version is released, @mochigithub you shouldn't experience this error anymore.

**Comment by taooceros** [comment] 2021-05-25 09:22
🤔 weird, we have fixed it? 

> you must have been looking at the dev branch code?

Yes I do take a look on the dev branch code....but do we change anything around the actionkeyword for 1.8.0? Anyway, it would be great to notice that we have fixed it.

**Comment by jjw24** [comment] 2021-05-25 10:36
nop, I am wrong 🤣  

it exists in dev too. The key is once you delete all action keyword, you exit flow via query 'exit', and then you will be able to repro the error.

**Closed** 2021-05-27 10:32 UTC
Labels: bug
