### ISSUE TITLE
BUG: Crashes when pressing any letter

### ISSUE THREAD

**Issue by Arthur997** [Flow-Launcher/Flow.Launcher#1658] opened 2022-12-15 11:37 UTC
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

I have the last version but still crashing when pressing any letter, here ir the log:

Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/15/2022 08:34:16
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: O servidor RPC não está disponível. (0x800706BA)
 ---> System.Runtime.InteropServices.COMException (0x800706BA): O servidor RPC não está disponível. (0x800706BA)
   at Microsoft.Search.Interop.CSearchQueryHelperClass.get_ConnectionString()
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.SearchAsync(String search, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 62
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 88
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

v1.10

### Windows Build Number

10.0.19043.1288

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment] 2022-12-15 11:42
Same as #1630

Can you try this build and let me know if the issue is fixed please https://ci.appveyor.com/api/buildjobs/u00is5g7sgpwb246/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

**Comment by Arthur997** [comment] 2022-12-15 12:31
Thanks for the speed at respond. The issue appear after some use, i'll try this build for some time. I let you now if it happens again.

**Comment by jjw24** [comment] 2022-12-15 21:08
If it happens again after using the build, please let me know in issue 1628 linked above.

Closing due to duplication.

**Closed by jjw24** 2022-12-15 21:08 UTC
Labels: bug
