### ISSUE TITLE
BUG: Always Start Typing in English Mode - not work

### ISSUE THREAD

**Issue by Alexnoj** [Flow-Launcher/Flow.Launcher#2569] opened 2024-02-13 06:57 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I enable in options 'Always Start Typing in English Mode' when the launcher opened its not change the languge to english automatically.

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.17.1

### Windows Build Number

22621.3007

### Error Log

08:52:17.1496+02:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "AE2E89611857AD4D6FA76D59827AE2E1DD8BC4F9",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.17.2-full.nupkg",
  "Query": null,
  "Filesize": 105388595,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "AE2E89611857AD4D6FA76D59827AE2E1DD8BC4F9 FlowLauncher-1.17.2-full.nupkg 105388595",
  "Version": {
    "Version": "1.17.2.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
08:52:25.3765+02:00 - INFO  - Updater.UpdateApp - Update success:New version 1.17.2 is available, would you like to restart Flow Launcher to use the update?
08:52:27.9797+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
08:52:27.9797+02:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
08:52:27.9797+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
08:52:28.0547+02:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
08:52:28.0547+02:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
08:52:28.0547+02:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------

**Comment by z1nc0r3** [comment] 2024-02-13 17:06
Couldn't reproduce. Any specific way to reproduce the issue?

**Comment by Alexnoj** [comment] 2024-02-14 07:28
What can help?

**Comment by VictoriousRaptor** [comment] 2024-02-21 01:09
Please check [#2108](https://github.com/Flow-Launcher/Flow.Launcher/issues?q=is%3Aissue+english+mode) and see if your issue is the same as we addressed in that issue.

**Comment by Alexnoj** [comment] 2024-03-03 10:34
> Please check [#2108](https://github.com/Flow-Launcher/Flow.Launcher/issues/2108) and see if your issue is the same as we addressed in that issue.

Same issue. Thanks

**Comment by jjw24** [comment] 2024-03-08 10:23
Closing since same issue, please track over at 2108

**Closed by jjw24** 2024-03-08 10:23 UTC
Labels: bug, Waiting for response
