### ISSUE TITLE
Flow Launcher error

### ISSUE THREAD

**Issue by LtheHuman** [Flow-Launcher/Flow.Launcher#1811] opened 2023-01-18 07:40 UTC
[2023-01-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10443382/2023-01-18.txt)

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/18/2023 08:38:40
Exception:
System.NotSupportedException: 'Alt+LeftAlt' key and modifier combination is not supported for KeyGesture.
   at System.Windows.Input.KeyGesture..ctor(Key key, ModifierKeys modifiers, String displayString, Boolean validateGesture)
   at System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Flow.Launcher.Converters.StringToKeyBindingConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\projects\flow-launcher\Flow.Launcher\Converters\StringToKeyBindingConverter.cs:line 15
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by VictoriousRaptor** [comment] 2023-01-18 08:42
Dupe of #1755. Please check https://github.com/Flow-Launcher/Flow.Launcher/issues/1755#issuecomment-1368983887_ for a possible solution.

**Comment by LtheHuman** [comment] 2023-01-18 08:49
Thanks, it worked :)

**Closed** 2023-01-18 21:08 UTC
