### ISSUE TITLE
Many exceptions in log file post 1.7 update

### ISSUE THREAD

**Issue by deefrawley** [Flow-Launcher/Flow.Launcher#322] opened 2021-02-03 05:52 UTC
**Describe the bug/issue**
Just upgraded to v1.7 and getting a lot of exceptions in the log file. My currency converter plugin (python) also isn't working, though other plugins seem ok.

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Flow Launcher version: 1.7
```
**Flow Launcher Error Log**

Attached.

[2021-02-03.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/5916374/2021-02-03.txt)

**Comment by taooceros** [comment] 2021-02-03 07:52
```
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|-------------------------- Begin exception --------------------------
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Query Error
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception full name:
 <System.MissingMethodException>
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception message:
 <Method not found: 'Flow.Launcher.Infrastructure.MatchResult Flow.Launcher.Infrastructure.StringMatcher.FuzzySearch(System.String, System.String)'.>
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception stack trace:
 <   at Flow.Launcher.Plugin.Everything.Main.CreateResult(String keyword, SearchResult searchResult)
   at Flow.Launcher.Plugin.Everything.Main.Query(Query query) in C:\Workbench\Git\delete\Flow.Launcher.Plugin.Everything\Main.cs:line 55>
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception source:
 <Flow.Launcher.Plugin.Everything>
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception target site:
 <Flow.Launcher.Plugin.Result CreateResult(System.String, Flow.Launcher.Plugin.Everything.Everything.SearchResult)>
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception HResult:
 <-2146233069>
2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|-------------------------- End exception --------------------------
```
This may due to the Interface changed in v1.7.0. I will update everything plugin to accomodate the change. But that's weird because it doesn't happen when we are testing.

**Comment by taooceros** [comment] 2021-02-03 07:54
```
2021-02-03 15:11:42.8257|ERROR|JsonRPCPlugin.Query|-------------------------- Begin exception --------------------------
2021-02-03 15:11:42.8257|ERROR|JsonRPCPlugin.Query|Exception when query <cc>
2021-02-03 15:11:42.8257|ERROR|JsonRPCPlugin.Query|Exception full name:
 <System.InvalidOperationException>
2021-02-03 15:11:42.8257|ERROR|JsonRPCPlugin.Query|Exception message:
 <The JSON property name for 'Flow.Launcher.Core.Plugin.JsonRPCQueryResponseModel.Result' collides with another property.>
2021-02-03 15:11:42.8368|ERROR|JsonRPCPlugin.Query|Exception stack trace:
 <   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(JsonClassInfo jsonClassInfo, JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.DeserializedResult(String output) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 66
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.Query(Query query) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 39>
2021-02-03 15:11:42.8368|ERROR|JsonRPCPlugin.Query|Exception source:
 <System.Text.Json>
2021-02-03 15:11:42.8368|ERROR|JsonRPCPlugin.Query|Exception target site:
 <Void ThrowInvalidOperationException_SerializerPropertyNameConflict(System.Text.Json.JsonClassInfo, System.Text.Json.JsonPropertyInfo)>
2021-02-03 15:11:42.8368|ERROR|JsonRPCPlugin.Query|Exception HResult:
 <-2146233079>
2021-02-03 15:11:42.8368|ERROR|JsonRPCPlugin.Query|-------------------------- End exception --------------------------
```
This seems caused by the JSON library change.

**Comment by taooceros** [comment] 2021-02-03 07:56
The reason that your plugin may not work may caused by the issue of JSONRPC issue. I will take a look on that, and reach out soon.
Thank you so much for reporting the issue, and I am sorry for the inconvenience.

**Comment by taooceros** [comment] 2021-02-03 08:05
I don't understand why these various issue doesn't happen when we are testing. I will mark v1.7.0 as pre-release until this has been fixed.
So sorry for the inconvience.

**Comment by deefrawley** [comment] 2021-02-03 08:35
No worries. I don't do any coding in VS / dot net (just python and VS Code) so perhaps I don't have the libraries and SDKs that you guys use. I can do a full uninstall/fresh reinstall of Flow if you're interested to see what happens?

**Comment by jjw24** [comment] 2021-02-03 08:59
> ```
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|-------------------------- Begin exception --------------------------
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Query Error
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception full name:
>  <System.MissingMethodException>
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception message:
>  <Method not found: 'Flow.Launcher.Infrastructure.MatchResult Flow.Launcher.Infrastructure.StringMatcher.FuzzySearch(System.String, System.String)'.>
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception stack trace:
>  <   at Flow.Launcher.Plugin.Everything.Main.CreateResult(String keyword, SearchResult searchResult)
>    at Flow.Launcher.Plugin.Everything.Main.Query(Query query) in C:\Workbench\Git\delete\Flow.Launcher.Plugin.Everything\Main.cs:line 55>
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception source:
>  <Flow.Launcher.Plugin.Everything>
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception target site:
>  <Flow.Launcher.Plugin.Result CreateResult(System.String, Flow.Launcher.Plugin.Everything.Everything.SearchResult)>
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|Exception HResult:
>  <-2146233069>
> 2021-02-03 15:11:42.1959|ERROR|EverythingPlugin.Query|-------------------------- End exception --------------------------
> ```
> 
> This may due to the Interface changed in v1.7.0. I will update everything plugin to accomodate the change. But that's weird because it doesn't happen when we are testing.

This one maybe because Everything plugin packs its own infrastructure dll if i remember correctly, which contains a very old version of fuzzy search

**Comment by jjw24** [comment] 2021-02-03 09:10
> I don't understand why these various issue doesn't happen when we are testing. I will mark v1.7.0 as pre-release until this has been fixed.
> So sorry for the inconvience.

these exceptions are caused from the Everything and CurrencyCoverter plugin. Everything throws a missing method, which maybe due to the old dll, and CC throws the json dll collision exception, which is unknown to me. Each plugin uses its own dll library unless it's also referenced in the Plugin project, which then the AssemblyLoader will update the path to the dll path in from the Plugin project.

**Comment by taooceros** [comment] 2021-02-03 09:18
![image](https://user-images.githubusercontent.com/45326534/106724988-b5e77000-65bd-11eb-94d6-1abb7473af1b.png)
Get an error when testing

**Comment by jjw24** [comment] 2021-02-03 09:22
this is a python plugin, and those libraries such as the one in screenshot => dotenv requires you to use python's pip to install. if you dont know python, i can take a look

**Comment by taooceros** [comment] 2021-02-03 09:42
Oh I get it. I can take a try, since I think the main issue is Json

**Comment by taooceros** [comment] 2021-02-03 09:45
ok, find the issue.
![image](https://user-images.githubusercontent.com/45326534/106728579-73279700-65c1-11eb-9406-f749625c71e6.png)
Why there is two Result here

**Comment by taooceros** [comment] 2021-02-03 09:55
I think this is a design issue....We are not supposed to have two property that has the same name but with different type and meaning even though we use `new` to conver it.

**Comment by taooceros** [comment] 2021-02-03 09:58
@deefrawley https://ci.appveyor.com/api/buildjobs/vuoqy82qn9ru2x5t/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.0.exe Please take a try. In my computer, it fixes the python plugin issue.

**Comment by jjw24** [comment] 2021-02-03 10:05
> I think this is a design issue....We are not supposed to have two property that has the same name but with different type and meaning even though we use `new` to conver it.

from reading, you could with old json, new json you can't. That's why this issue surfaced.

**Comment by taooceros** [comment] 2021-02-03 10:06
Yes, that's the issue.

**Comment by deefrawley** [comment] 2021-02-03 22:14
Fresh install of @taooceros package above, with a clean install of the currency converter plugin and the Everything plugin and all works, no exceptions in the log except what looks like some indexing exceptions that end with 

`Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded`

which I'm pretty sure I've seen before.
Thanks all!

**Comment by taooceros** [comment] 2021-02-03 22:20
So it works?

**Comment by taooceros** [comment] 2021-02-03 22:28
I think the everything issue has also been resolved in another resipository, so I will close this.

**Closed by taooceros** 2021-02-03 22:28 UTC
Labels: bug
