### ISSUE TITLE
Toast Notification error with recent Windows 11 update 22H2

### ISSUE THREAD

**Issue by Moonlight2511** [Flow-Launcher/Flow.Launcher#2054] opened 2023-04-17 15:23 UTC
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/17/2023 22:38:39
Exception:
System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: Cannot create a stable subkey under a volatile parent key.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 35
   at Flow.Launcher.PublicAPIInstance.<>c__DisplayClass13_0.<ShowMsg>b__0() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 97
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.PublicAPIInstance.ShowMsg(String title, String subTitle, String iconPath, Boolean useMainWindowAsOwner) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 95
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 44
   at Flow.Launcher.P
lugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 44
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-04-17.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11252590/2023-04-17.txt)

**Comment by Moonlight2511** [comment] 2023-04-17 15:23
[2023-04-17.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11252346/2023-04-17.txt)

**Comment by deefrawley** [comment] 2023-04-19 02:23
Hi, could you please try installing the prerelease version and let us know if that fixes the issue?

https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.14.0.7149

Thanks

**Comment by Moonlight2511** [comment] 2023-04-19 11:42
> 
![image](https://user-images.githubusercontent.com/131010068/233063972-398a27f8-eccb-46c3-b7bc-dfec69eda64c.png)
i can download now but its still doesn't work

**Comment by Moonlight2511** [comment] 2023-04-19 13:25
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/131010068/233063972-398a27f8-eccb-46c3-b7bc-dfec69eda64c.png) i can download now but its still doesn't work, like its downloaded but the launcher still say everything service is not running
> 
> What if you click that result? Does it still raise an error? And I see your Everything on the desktop, did you manually downloaded it or you downloaded by clicking the result?

after i restart my pc is work, no error anymore. Tysm

**Comment by jjw24** [comment] 2023-04-21 00:21
Please update to v1.14.1 hotfix to see if the issue is resolved while we work on a permanent fix to address this.

**Comment by Garulf** [comment] 2023-04-22 19:37
Has anyone with this issue tried the newest version yet?

Please give us a heads up if this did not fix your problem. 

Thank you.

**Comment by mtsbh** [comment] 2023-04-27 18:56
Can we make Flow work with Everything 1.5a?

**Comment by deefrawley** [comment] 2023-04-28 01:14
@Moonlight2511 @foreverfallinluv @hungnvd59 @nvt1509 @thisisTin @Whisper1101 @LLLLLC
Can you respond and let us know if the hotfix has solved this problem? Thanks.

**Comment by foreverfallinluv** [comment] 2023-04-29 04:12
> @Moonlight2511 @foreverfallinluv @hungnvd59 @nvt1509 @thisisTin @Whisper1101 @LLLLLC Can you respond and let us know if the hotfix has solved this problem? Thanks.

Hi ! 
Emmmmm, it doesn't fix on my PC, i had try but it not working
Thanks .

**Comment by thisisTin** [comment] 2023-04-29 04:16
> Has anyone with this issue tried the newest version yet?
> 
> Please give us a heads up if this did not fix your problem.
> 
> Thank you.
Sorry for not reply you because i have a lot of work to do.
Thank you for your help. I'll will try the newest update right now.

**Comment by thisisTin** [comment] 2023-04-29 04:18
> > Has anyone with this issue tried the newest version yet?
> > Please give us a heads up if this did not fix your problem.
> > Thank you.
> > Sorry for not reply you because i have a lot of work to do.
> > Thank you for your help. I'll will try the newest update right now.

Well, it's worked. Thank you for your help.
Tin.

**Comment by azaelbr** [comment] 2023-05-01 02:48
v1.14.1  here and the plugin dont work and service is not running.

**Comment by Moonlight2511** [comment] 2023-05-01 15:46
> @Moonlight2511 @foreverfallinluv @hungnvd59 @nvt1509 @thisisTin @Whisper1101 @LLLLLC Can you respond and let us know if the hotfix has solved this problem? Thanks.

umm i tried again but the plugin still didn't work

**Comment by azaelbr** [comment] 2023-06-16 10:07
Anyone found a fix for this problem? I’m using the lasted update and still not working.

**Comment by VictoriousRaptor** [comment] 2023-06-16 16:52
> Anyone found a fix for this problem? I’m using the lasted update and still not working.

Please fire a new issue and post your log. I'm sure the notification issue is fixed in the workaround PR. This issue is just to notify we don't have a perfect solution yet.

**Comment by khalid949** [comment] 2023-10-09 04:24
08:16:23.1591+04:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
08:16:23.1633+04:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.16.2
OS Version: 22621.2361
IntPtr Length: 8
x64: True
08:16:24.1553+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <21ms>
08:16:24.1553+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <6ms>
08:16:24.1884+04:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
08:16:24.1884+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <44ms>
08:16:24.2013+04:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <20ms>
08:16:24.2013+04:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <136>
08:16:24.2013+04:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <68>
08:16:24.2200+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <3ms>
08:16:24.2200+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <33ms>
08:16:24.2329+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <88ms>
08:16:24.2345+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <111ms>
08:16:24.2345+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <102ms>
08:16:24.2518+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <32ms>
08:16:24.2518+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <119ms>
08:16:24.2922+04:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
08:16:24.2922+04:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
08:16:24.2922+04:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
08:16:24.3008+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <72ms>
08:16:24.5613+04:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 133 plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
08:16:24.5673+04:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <417ms>
08:16:25.0477+04:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
Node Path: 
08:16:25.5915+04:00 - FATAL - UnHandledException - 
## Exception

```
System.IO.IOException: The process cannot access the file because it is being used by another process.
   Source: System.Private.CoreLib
   TargetAssembly: System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
   TargetModule: System.Private.CoreLib.dll
   TargetSite: Void ReplaceFile(System.String, System.String, System.String, Boolean)
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 124
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   Source: System.Private.CoreLib
   TargetAssembly: System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
   TargetModule: System.Private.CoreLib.dll
   TargetSite: System.Object Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Flow.Launcher.PublicAPIInstance.SavePluginSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 198
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 62
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 105
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment] 2024-01-13 20:48
This issue appears to be resolved. Closing.

**Closed** 2024-01-13 20:48 UTC
Labels: bug, High Priority, keep-fresh
