### ISSUE TITLE
BUG: Incorrect display of searched file/directory

### ISSUE THREAD

**Issue by reko001** [Flow-Launcher/Flow.Launcher#1821] opened 2023-01-19 15:42 UTC
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

After creating a file, it is displayed as file when searched. If it is removed, and a directory with the same name is created, it is still displayed as file in searching window. The same goes if the directory is created first and file second.

### To Reproduce

1. Create file named "test" in indexed directory
2. Search for this file -> result: it is displayed as file
3. Remove this file
4. Create directory named "test" in the same directory
5. Search for this directory
6. Current result: it is displayed as file
7. Expected result: it is displayed as directory

### Flow Launcher Version

1.11.0

### Windows Build Number

10.0.22621.1105

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by z1nc0r3** [comment] 2023-01-20 11:16
I followed the steps but couldn't reproduce the error.
Which search engine do you use in the explorer plugin?

**Comment by VictoriousRaptor** [comment] 2023-01-20 11:40
I think it's related to index search engine. It may take a while for Windows Search to reindex. And you need to type "test" again to trigger a re-query, or Flow still shows the results from the first search.

**Comment by jjw24** [comment] 2023-02-01 20:19
Thanks for reporting this @reko001

This is indeed a mismatch between when the index refreshes and when Flow's results are updated. I don't think this is something we can control, so closing this.

Please reopen if otherwise.

**Closed by jjw24** 2023-02-01 20:19 UTC
Labels: bug
