### ISSUE TITLE
Can't install everything

### ISSUE THREAD

**Issue by thisisTin** [Flow-Launcher/Flow.Launcher#2055] opened 2023-04-17 17:00 UTC
[2023-04-17.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11253369/2023-04-17.txt)

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/17/2023 23:59:25
Exception:
System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: Cannot create a stable subkey under a volatile parent key.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 35
   at Flow.Launcher.PublicAPIInstance.<>c__DisplayClass13_0.<ShowMsg>b__0() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 97
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.PublicAPIInstance.ShowMsg(String title, String subTitle, String iconPath, Boolean useMainWindowAsOwner) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 95
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 44
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 44
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment] 2023-04-18 00:59
Hi. Do you have the latest Windows updates?

**Comment by thisisTin** [comment] 2023-04-18 01:19
yes i do, i just install it yesterday

**Comment by deefrawley** [comment] 2023-04-18 03:36
Was Flow working before the update?

**Comment by thisisTin** [comment] 2023-04-18 03:42
> Was Flow working before the update?
i've just installed Flow Launcher yesterday so i don't know.

**Comment by thisisTin** [comment] 2023-04-18 05:24
> > > Was Flow working before the update?
> > > i've just installed Flow Launcher yesterday so i don't know.
> 
> You can manually download and install Everything from their website. We'll look into this issue.

Well i tried to install it but it keep saying this:
![image](https://user-images.githubusercontent.com/93574055/232678790-3ff02011-50da-4bac-a1da-b21060a99a5f.png)
 This is how i install it:
 
![image](https://user-images.githubusercontent.com/93574055/232678915-3b6162f5-cb22-4cf4-ba5a-45c6bd3a8316.png)

**Comment by nvt1509** [comment] 2023-04-18 19:51
> > > > Was Flow working before the update?
> > > > i've just installed Flow Launcher yesterday so i don't know.
> > 
> > 
> > You can manually download and install Everything from their website. We'll look into this issue.
> 
> Well i tried to install it but it keep saying this: ![image](https://user-images.githubusercontent.com/93574055/232678790-3ff02011-50da-4bac-a1da-b21060a99a5f.png) This is how i install it:
> 
> ![image](https://user-images.githubusercontent.com/93574055/232678915-3b6162f5-cb22-4cf4-ba5a-45c6bd3a8316.png)

bác ơi giờ xài được chưa bác hay nó vẫn lỗi y vậy?

**Comment by deefrawley** [comment] 2023-04-18 23:51
Could you please try installing the prerelease version of Flow which has some updates that we would like to test against for this issue.
If you download the install from our prerelease page and let us know if this helps:

https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.14.0.7145

Thanks

**Comment by thisisTin** [comment] 2023-04-19 05:29
> > > > > Was Flow working before the update?
> > > > > i've just installed Flow Launcher yesterday so i don't know.
> > > 
> > > 
> > > You can manually download and install Everything from their website. We'll look into this issue.
> > 
> > 
> > Well i tried to install it but it keep saying this: ![image](https://user-images.githubusercontent.com/93574055/232678790-3ff02011-50da-4bac-a1da-b21060a99a5f.png) This is how i install it:
> > ![image](https://user-images.githubusercontent.com/93574055/232678915-3b6162f5-cb22-4cf4-ba5a-45c6bd3a8316.png)
> 
> bác ơi giờ xài được chưa bác hay nó vẫn lỗi y vậy?

còn á bác vẫn bị để cài ver thấp hơn

**Comment by thisisTin** [comment] 2023-04-19 05:46
> Could you please try installing the prerelease version of Flow which has some updates that we would like to test against for this issue. If you download the install from our prerelease page and let us know if this helps:
> 
> https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.14.0.7145
> 
> Thanks

i tried it and it didn't work. My windows version is
![image](https://user-images.githubusercontent.com/93574055/232977900-1a5e3644-7791-40af-b669-6baa8037054d.png)

**Comment by nvt1509** [comment] 2023-04-19 09:08
ô thế bác tải cái phiên bản trước của bọn nó cũng k được luôn ạ :))


Vào Th 4, 19 thg 4, 2023 vào lúc 12:46 Tran Trong Tin <
***@***.***> đã viết:

**Comment by Garulf** [comment] 2023-04-19 16:07
Looks like a duplicate of #2054 (And many others). Please continue discussion there. Thank you.

**Closed by Garulf** 2023-04-19 16:07 UTC
