### ISSUE TITLE
When starting windows it displays the error screen Error: System.NotSupportedException: 'Alt+LeftAlt' key and modifier combination is not supported for KeyGesture.

### ISSUE THREAD

**Issue by tiagodefariasantos** [Flow-Launcher/Flow.Launcher#1812] opened 2023-01-18 11:27 UTC
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\tiago\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/18/2023 08:06:17
Exception:
System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Input.InputBindingCollection' threw an exception.
 ---> System.NotSupportedException: 'Alt+LeftAlt' key and modifier combination is not supported for KeyGesture.
   at System.Windows.Input.KeyGesture..ctor(Key key, ModifierKeys modifiers, String displayString, Boolean validateGesture)
   at System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Flow.Launcher.Converters.StringToKeyBindingConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\projects\flow-launcher\Flow.Launcher\Converters\StringToKeyBindingConverter.cs:line 15
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.OnInheritanceContextChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at MS.Internal.InheritanceContextChangedEventManager.OnInheritanceContextChanged(Object sender, EventArgs args)
   at System.Windows.DependencyObject.OnInheritanceContextChanged(EventArgs args)
   at MS.Internal.InheritanceContextHelper.AddInheritanceContext(DependencyObject newInheritanceContext, DependencyObject value, Boolean& hasMultipleInheritanceContexts, DependencyObject& inheritanceContext)
   at System.Windows.Input.InputBinding.AddInheritanceContext(DependencyObject context, DependencyProperty property)
   at System.Windows.DependencyObject.ProvideSelfAsInheritanceContext(DependencyObject doValue, DependencyProperty dp)
   at MS.Internal.InheritanceContextHelper.ProvideContextForObject(DependencyObject context, DependencyObject newValue)
   at System.Windows.Input.InputBindingCollection.Add(InputBinding inputBinding)
   at System.Windows.Input.InputBindingCollection.System.Collections.IList.Add(Object inputBinding)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Flow.Launcher.MainWindow.InitializeComponent() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml:line 1
   at Flow.Launcher.MainWindow..ctor(Settings settings, MainViewModel mainVM) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 51
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 81
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by VictoriousRaptor** [comment] 2023-01-18 15:40
Dupe of #1755. Please check https://github.com/Flow-Launcher/Flow.Launcher/issues/1755#issuecomment-1368983887_ for a possible solution.

**Closed** 2023-01-18 21:08 UTC
